// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Accounts      string
	Comments      string
	Posts         string
	Relationships string
}{
	Accounts:      "accounts",
	Comments:      "comments",
	Posts:         "posts",
	Relationships: "relationships",
}
