// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Comments", testCommentsUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("Relationships", testRelationshipsUpsert)
}
